[package]
name = "coreutils_auth"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
